
development:
  adapter: postgresql
  host: localhost
  port: 5432
  username: <%= APP_CONFIG["db_username"] %>
  password: <%= APP_CONFIG["db_password"] %>
  database: app_dev
  schema_search_path: public
  encoding: utf8
  template: template1

test:
  adapter: postgresql
  host: localhost
  port: 5432
  username: Matt
  password: password
  database: app_test
  schema_search_path: public
  encoding: utf8
  template: template1


production:
  adapter: postgresql
  host: localhost
  port: 5432
  username: Matt
  password: password
  database: app_prod
  schema_search_path: public
  encoding: utf8
  template: template1
